### ISSUE TITLE
无法全屏！！

### ISSUE THREAD

**Issue by 2422247006** [seeksdream/relation-graph#267]
无法全屏 报错
Error in v-on handler: "TypeError: Cannot read properties of undefined (reading 'toggle')"

found in

---> <GraphMiniToolBar>
       <SeeksRelationGraph>
         <Root>

vue.js:1906 TypeError: Cannot read properties of undefined (reading 'toggle')
    at Pt.fullscreen (relation-graph.min.js:1692:91)
    at click (relation-graph.min.js:4287:48)
    at invokeWithErrorHandling (vue.js:1872:28)
    at HTMLDivElement.invoker (vue.js:2197:16)
    at original._wrapper

**Comment by seeksdream** [comment]
能提供更多信息吗？比如你使用的是vue3还是vue2、使用的relation-graph版本

**Comment by seeksdream** [comment]
这是一个bug，目前已经解决，请更新到2.1.42或者2.2.0即可.
